{
 "title": "ActiveMQ",
 "tags": [
  "template",
  "webservices"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "SystemInstance", "query": "servers.*" }
  ]
 },
 "panels": [
  {
   "title": "Average Message Size",
   "type": "singlestat",
   "description": "The current average message size.",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "target": "servers.$SystemInstance.ActiveMQ.AverageMessageSize"
    }
   ]
  },
  {
   "title": "Max Message Size",
   "type": "singlestat",
   "description": "The maximum message size since the last time the broker was restarted.",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "target": "servers.$SystemInstance.ActiveMQ.MaxMessageSize"
    }
   ]
  },
  {
   "title": "Current Connections",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 10, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "servers.$SystemInstance.ActiveMQ.TotalConnectionsCount"
    }
   ]
  },
  {
   "title": "Dequeued Messages",
   "type": "singlestat",
   "description": "Current dequeued message rate for the last minute.",
   "gridPos": { "h": 7, "w": 5, "x": 14, "y": 0 },
   "format": "opm",
   "valueName": "delta",
   "targets": [
    {
     "target": "servers.$SystemInstance.ActiveMQ.TotalDequeueCount"
    }
   ]
  },
  {
   "title": "Enqueued Messages",
   "type": "singlestat",
   "description": "Current enqueued message rate for the last minute.",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 0 },
   "format": "opm",
   "valueName": "delta",
   "targets": [
    {
     "target": "servers.$SystemInstance.ActiveMQ.TotalEnqueueCount"
    }
   ]
  },
  {
   "title": "ActiveMQ Message Rate",
   "type": "graph",
   "description": "The number of messages  [de]queued per second.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "alias": "Used",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "attributeName" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "heap",
     "query": "SELECT mean(\"committed\") FROM \"heap\" WHERE $timeFilter GROUP BY time($__interval), \"hostname\" fill(null)",
     "select": [
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "attributeName", "operator": "=", "value": "NonHeapMemoryUsage" }
     ],
     "target": "aliasSub(scaleToSeconds(derivative(servers.$SystemInstance.ActiveMQ.Total*queueCount), 1), '.*servers.(\\w+?)\\.(\\w+?)\\.(\\w+?)', '\\1 - \\3')"
    }
   ]
  },
  {
   "title": "ActiveMQ Connections",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "Used",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "attributeName" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "heap",
     "query": "SELECT mean(\"committed\") FROM \"heap\" WHERE $timeFilter GROUP BY time($__interval), \"hostname\" fill(null)",
     "select": [
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "attributeName", "operator": "=", "value": "NonHeapMemoryUsage" }
     ],
     "target": "aliasSub(servers.$SystemInstance.ActiveMQ.TotalConnectionsCount, '.*servers.(\\w+?)\\.(\\w+?)\\.(\\w+?)', '\\1 - \\3')"
    }
   ]
  }
 ]
}