{
 "title": "NetApp E-Series Overview",
 "tags": [ "NetAppESeries" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "ESystem", "query": "storage.eseries.*" },
   { "name": "TopResources", "query": "1,2,3,4,5,6,8,10,15,20,40" }
  ]
 },
 "panels": [
  { "title": "Header", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 15, "x": 0, "y": 1 },
   "content": "# E-Series Performance Monitoring\n\nThis is the landing page for the E-Series Performance Monitor. You can view all of the dashboards that we provide over on the right.\n\nIf you aren't getting any monitored systems or data in your dashbard[s], refer to the README and ensure that you have properly added your E-Series systems to the configuration file with the correct passwords."
  },
  { "title": "E-Series Dashboards", "type": "dashlist", "gridPos": { "h": 5, "w": 9, "x": 15, "y": 1 } },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Read Cache Utilization",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "target": "averageSeries(highestAverage(storage.eseries.$ESystem.volume_statistics.*.readCacheUtilization, $TopResources))"
    }
   ]
  },
  {
   "title": "Write Cache Utilization",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "target": "averageSeries(highestAverage(storage.eseries.$ESystem.volume_statistics.*.writeCacheUtilization, $TopResources))"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "highestAverage(groupByNode(storage.eseries.$ESystem.volume_statistics.*.combinedResponseTime, 2, 'avg'), $TopResources)"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "MBs" }
   ],
   "targets": [
    {
     "target": "highestAverage(groupByNode(storage.eseries.$ESystem.volume_statistics.*.combinedThroughput, 2, 'sum'), $TopResources)"
    }
   ]
  },
  {
   "title": "IOPs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "target": "highestAverage(groupByNode(storage.eseries.$ESystem.volume_statistics.*.combinedIOps, 2, 'sum'), $TopResources)"
    }
   ]
  },
  {
   "title": "Read Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "highestAverage(groupByNode(storage.eseries.$ESystem.volume_statistics.*.readResponseTime, 2, 'avg'), $TopResources)"
    }
   ]
  },
  {
   "title": "Read Data",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 17 },
   "yaxes": [
    { "format": "MBs" }
   ],
   "targets": [
    {
     "target": "highestAverage(groupByNode(storage.eseries.$ESystem.volume_statistics.*.readThroughput, 2, 'sum'), $TopResources)"
    }
   ]
  },
  {
   "title": "Read IOPs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "target": "highestAverage(groupByNode(storage.eseries.$ESystem.volume_statistics.*.readIOps, 2, 'sum'), $TopResources)"
    }
   ]
  },
  {
   "title": "Write Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "highestAverage(groupByNode(storage.eseries.$ESystem.volume_statistics.*.writeResponseTime, 2, 'avg'), $TopResources)"
    }
   ]
  },
  {
   "title": "Write Data",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 24 },
   "yaxes": [
    { "format": "MBs" }
   ],
   "targets": [
    {
     "target": "highestAverage(groupByNode(storage.eseries.$ESystem.volume_statistics.*.writeThroughput, 2, 'sum'), $TopResources)"
    }
   ]
  },
  {
   "title": "Write IOPs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 24 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "target": "highestAverage(groupByNode(storage.eseries.$ESystem.volume_statistics.*.writeIOps, 2, 'sum'), $TopResources)"
    }
   ]
  }
 ]
}