{
 "title": "Statistics",
 "tags": [
  "template",
  "webservices"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "SystemInstance", "query": "servers.*" }
  ]
 },
 "panels": [
  {
   "title": "Historical Statistics",
   "type": "singlestat",
   "description": "The number of days that we are preserving the statistics for later retrieval.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "servers.$SystemInstance.StatsManager.HxDaysToSave"
    }
   ]
  },
  {
   "title": "Polling Interval",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "servers.$SystemInstance.StatsManager.PollingInterval"
    }
   ]
  },
  {
   "title": "Fetch Times",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "divideSeries(movingAverage(servers.$SystemInstance.StatsManager.LastHistoricalFetchTime, '5min'), #A)",
     "targetFull": "divideSeries(movingAverage(servers.$SystemInstance.StatsManager.LastHistoricalFetchTime, '5min'), scale(servers.$SystemInstance.StatsManager.PollingInterval, 1000))"
    }
   ]
  },
  {
   "title": "Statistics Fetch Time",
   "type": "graph",
   "description": "The amount of time it took us to make the statistics collection.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "DeviceManager",
     "select": [
      [
       { "params": [ "RequestCount" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "target": "aliasByMetric(servers.$SystemInstance.StatsManager.LastHistoricalFetchTime)"
    }
   ]
  }
 ]
}