{
 "title": "Storage System",
 "tags": [
  "template",
  "webservices"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "SystemInstance", "query": "servers.*" },
   { "name": "StorageSystem", "query": "*.*.StorageSystems.*" }
  ]
 },
 "panels": [
  {
   "title": "Active Connections (HeatMap)",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "target": "servers.$SystemInstance.StorageSystems.$StorageSystem.ActveConnections"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "none", "label": "Connection Count" }
   ],
   "targets": [
    {
     "alias": "$tag_typeName",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "typeName" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "StorageSystems",
     "select": [
      [
       { "params": [ "OpenConnections" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "aliasByNode(summarize(highestAverage(servers.$SystemInstance.StorageSystems.$StorageSystem.ActveConnections, 5), '1m', 'avg', 'false'), 3)"
    }
   ]
  },
  {
   "title": "Open Connections (HeatMap",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "target": "servers.$SystemInstance.StorageSystems.$StorageSystem.OpenConnections"
    }
   ]
  },
  {
   "title": "Open Connections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "none", "label": "Connection Count" }
   ],
   "targets": [
    {
     "alias": "$tag_typeName",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "typeName" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "StorageSystems",
     "select": [
      [
       { "params": [ "OpenConnections" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "aliasByNode(summarize(highestAverage(servers.$SystemInstance.StorageSystems.$StorageSystem.OpenConnections, 5), '1m', 'avg', false), 3)"
    }
   ]
  },
  {
   "title": "Storage Systems",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 18 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DeviceManager",
     "select": [
      [
       { "params": [ "SystemCount" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "servers.$SystemInstance.DeviceManager.SystemCount"
    }
   ]
  },
  {
   "title": "Online Storage Systems",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 18 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DeviceManager",
     "select": [
      [
       { "params": [ "OnlineSystemCount" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "servers.$SystemInstance.DeviceManager.OnlineSystemCount"
    }
   ]
  },
  {
   "title": "ObjectGraph Fetch Times (Average)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "typeName" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "StorageSystems",
     "select": [
      [
       { "params": [ "LastGraphFetchTime" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ],
     "target": "aliasByNode(removeBelowValue(summarize(highestAverage(servers.$SystemInstance.StorageSystems.$StorageSystem.LastGraphFetchTime, 5), '1m', 'avg', 'true'), 0.00001), 3)"
    }
   ]
  },
  {
   "title": "Graph Fetches (Top 5)",
   "type": "graph",
   "description": "The systems with the most change activity. This is measured by the number of objectGraph fetches we've had to make.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "DeviceManager",
     "select": [
      [
       { "params": [ "NumberOfSelectChannels" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "aliasByNode(summarize(removeBelowValue(highestAverage(derivative(servers.$SystemInstance.StorageSystems.$StorageSystem.GraphFetchCount), 5), 1), '15s', 'sum', true), 3)"
    }
   ]
  },
  {
   "title": "ObjectGraph Fetch Times (Average)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "typeName" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "StorageSystems",
     "select": [
      [
       { "params": [ "LastGraphFetchTime" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ],
     "target": "aliasByNode(removeBelowValue(highestAverage(*.*.StorageSystems.$StorageSystem.LastGraphFetchTime, 5), 0.00001), 3)"
    }
   ]
  }
 ]
}