{
 "title": "Storage System Detail",
 "tags": [
  "template",
  "webservices"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "SystemInstance", "query": "servers.*" },
   { "name": "StorageSystem", "query": "*.*.StorageSystems.*" }
  ]
 },
 "panels": [
  {
   "title": "Graph Fetches",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "delta",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DeviceManager",
     "select": [
      [
       { "params": [ "SystemCount" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "servers.$SystemInstance.StorageSystems.$StorageSystem.GraphFetchCount"
    }
   ]
  },
  {
   "title": "Graph Avg Fetch Time",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 0 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DeviceManager",
     "select": [
      [
       { "params": [ "SystemCount" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "servers.$SystemInstance.StorageSystems.$StorageSystem.LastGraphFetchTime"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "none", "label": "Connection Count" }
   ],
   "targets": [
    {
     "alias": "$tag_typeName",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "typeName" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "StorageSystems",
     "select": [
      [
       { "params": [ "OpenConnections" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "aliasByMetric(servers.$SystemInstance.StorageSystems.$StorageSystem.*Connections)"
    }
   ]
  }
 ]
}