{
 "title": "System View Dashboard",
 "tags": [ "NetAppESeries" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "System",
    "query": "SHOW TAG VALUES FROM \"major_event_log\" WITH KEY = \"sys_name\""
   }
  ]
 },
 "panels": [
  { "title": "Disks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Disks",
   "type": "table",
   "description": "List of disks on the selected system(s)",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "sys_tray_slot" ], "type": "tag" },
      { "params": [ "sys_name" ], "type": "tag" },
      { "params": [ "sys_tray" ], "type": "tag" }
     ],
     "measurement": "disks",
     "select": [
      [
       { "params": [ "readOps" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "sys_name", "operator": "=~", "value": "/^$System$/" }
     ]
    }
   ]
  },
  {
   "title": "Average Disk Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 9, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_sys_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sys_name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "disks",
     "select": [
      [
       { "params": [ "combinedResponseTime" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sys_name", "operator": "=~", "value": "/^$System$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Disk Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "MBs" }
   ],
   "targets": [
    {
     "alias": "$tag_sys_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sys_name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "disks",
     "select": [
      [
       { "params": [ "combinedThroughput" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "sys_name", "operator": "=~", "value": "/^$System$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Disk IOps",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 0 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "alias": "$tag_sys_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sys_name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "disks",
     "select": [
      [
       { "params": [ "combinedIOps" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "sys_name", "operator": "=~", "value": "/^$System$/" }
     ]
    }
   ]
  },
  { "title": "Volumes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Volumes",
   "type": "table",
   "description": "List of volumes on the selected system(s)",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 10 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "vol_name" ], "type": "tag" },
      { "params": [ "sys_name" ], "type": "tag" }
     ],
     "measurement": "volumes",
     "select": [
      [
       { "params": [ "readOps" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "sys_name", "operator": "=~", "value": "/^$System$/" }
     ]
    }
   ]
  },
  {
   "title": "Average Volume Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 9, "y": 10 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_sys_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sys_name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "volumes",
     "select": [
      [
       { "params": [ "combinedResponseTime" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sys_name", "operator": "=~", "value": "/^$System$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Volume Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 10 },
   "yaxes": [
    { "format": "MBs" }
   ],
   "targets": [
    {
     "alias": "$tag_sys_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sys_name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "volumes",
     "select": [
      [
       { "params": [ "combinedThroughput" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "sys_name", "operator": "=~", "value": "/^$System$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Volume IOps",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 10 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "alias": "$tag_sys_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sys_name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "volumes",
     "select": [
      [
       { "params": [ "combinedIOps" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "sys_name", "operator": "=~", "value": "/^$System$/" }
     ]
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Average CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 10, "w": 19, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_sys_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sys_name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "systems",
     "query": "SELECT \"cpuAvgUtilization\" FROM \"systems\" WHERE $timeFilter GROUP BY time($__interval), \"sys_name\" fill(none)",
     "select": [
      [
       { "params": [ "cpuAvgUtilization" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "sys_name", "operator": "=~", "value": "/^$System$/" }
     ]
    }
   ]
  },
  {
   "title": "Maximum CPU Utilization",
   "type": "table",
   "gridPos": { "h": 10, "w": 5, "x": 19, "y": 19 },
   "targets": [
    {
     "alias": "$tag_sys_name",
     "groupBy": [
      { "params": [ "sys_name" ], "type": "tag" }
     ],
     "measurement": "systems",
     "select": [
      [
       { "params": [ "maxCpuUtilization" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "sys_name", "operator": "=~", "value": "/^$System$/" }
     ]
    }
   ]
  },
  {
   "title": "Major Event Log",
   "type": "table",
   "gridPos": { "h": 10, "w": 15, "x": 0, "y": 29 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "sys_name" ], "type": "tag" }
     ],
     "measurement": "major_event_log",
     "query": "SELECT \"id\", \"location\", \"description\" FROM \"major_event_log\" WHERE (\"sys_name\" =~ /^$System$/) GROUP BY \"sys_name\"",
     "select": [
      [
       { "params": [ "id" ], "type": "field" }
      ],
      [
       { "params": [ "location" ], "type": "field" }
      ],
      [
       { "params": [ "description" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "sys_name", "operator": "=~", "value": "/^$System$/" }
     ]
    }
   ]
  },
  {
   "title": "System Failures",
   "type": "table",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 29 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "sys_name" ], "type": "tag" },
      { "params": [ "failure_type" ], "type": "tag" },
      { "params": [ "object_type" ], "type": "tag" }
     ],
     "measurement": "failures",
     "query": "SELECT \"id\", \"location\", \"description\" FROM \"major_event_log\" WHERE (\"sys_name\" =~ /^$System$/) GROUP BY \"sys_name\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "sys_name", "operator": "=~", "value": "/^$System$/" }
     ]
    }
   ]
  }
 ]
}