{
 "title": "Threads",
 "tags": [
  "template",
  "webservices"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "SystemInstance", "query": "servers.*" }
  ]
 },
 "panels": [
  {
   "title": "Threads",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "servers.$SystemInstance.Threading.ThreadCount"
    }
   ]
  },
  {
   "title": "Daemon Threads",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "servers.$SystemInstance.Threading.DaemonThreadCount"
    }
   ]
  },
  {
   "title": "Started Threads",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "servers.$SystemInstance.Threading.TotalStartedThreadCount"
    }
   ]
  },
  {
   "title": "Peak Threads",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "servers.$SystemInstance.Threading.PeakThreadCount"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 6, "w": 17, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "DeviceManager",
     "select": [
      [
       { "params": [ "RequestCount" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "target": "aliasByMetric(servers.$SystemInstance.Threading.ThreadCount)"
    },
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "DeviceManager",
     "select": [
      [
       { "params": [ "RequestCount" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "target": "aliasByMetric(servers.$SystemInstance.Threading.DaemonThreadCount)"
    }
   ]
  },
  {
   "title": "Thread Creations",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 17, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "scaleToSeconds(derivative(movingAverage(servers.$SystemInstance.Threading.TotalStartedThreadCount, '5min')), 60)"
    }
   ]
  }
 ]
}