{
 "title": "Top-Level",
 "tags": [
  "template",
  "webservices"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "SystemInstance", "query": "servers.*" }
  ]
 },
 "panels": [
  {
   "title": "Storage Systems",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DeviceManager",
     "select": [
      [
       { "params": [ "SystemCount" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "servers.$SystemInstance.DeviceManager.SystemCount"
    }
   ]
  },
  {
   "title": "Online Systems",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DeviceManager",
     "select": [
      [
       { "params": [ "SystemCount" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "asPercent(servers.$SystemInstance.DeviceManager.OnlineSystemCount, #B)",
     "targetFull": "asPercent(servers.$SystemInstance.DeviceManager.OnlineSystemCount, servers.$SystemInstance.DeviceManager.SystemCount)"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "singlestat",
   "description": "Total requests over the time interval.",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "diff",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DeviceManager",
     "select": [
      [
       { "params": [ "SystemCount" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "servers.$SystemInstance.DeviceManager.RequestCount"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "singlestat",
   "description": "Total requests over the time interval.",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "format": "ops",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DeviceManager",
     "select": [
      [
       { "params": [ "SystemCount" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "scaleToSeconds(derivative(servers.$SystemInstance.DeviceManager.RequestCount), 1)"
    }
   ]
  },
  {
   "title": "Request Count",
   "type": "graph",
   "description": "The requests over the time interval.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "DeviceManager",
     "select": [
      [
       { "params": [ "RequestCount" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "target": "aliasByMetric(smartSummarize(derivative(servers.$SystemInstance.DeviceManager.RequestCount), '15s', 'sum'))"
    }
   ]
  },
  {
   "title": "Select Channels",
   "type": "graph",
   "description": "The number of connections that we have open to storage-systems.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "DeviceManager",
     "select": [
      [
       { "params": [ "RequestCount" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "target": "aliasByMetric(servers.$SystemInstance.DeviceManager.NumberOfSelectChannels)"
    }
   ]
  }
 ]
}