{
 "title": "WSP Memory Dashboard",
 "tags": [
  "template",
  "webservices"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Threads", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "ThreadPool Metrics",
   "type": "graph",
   "description": "Our main thread pool used for state updates, etc. When this pool is blocked for any length of time, it can cause performance issues in other services.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(servers.*.DeviceManager.ThreadPoolSize)"
    },
    {
     "target": "aliasByMetric(servers.*.DeviceManager.ProcessingTaskCount)"
    }
   ]
  },
  {
   "title": "WebServer Threads",
   "type": "graph",
   "description": "Our Web Server has a finite number of threads allocated. Idle threads will eventually timeout, but can be recreated as needed. BLocked threads will queue requests at the Web Server level.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Threads" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(servers.*.WebServer.*ThreadCount)"
    }
   ]
  },
  { "title": "ClassLoading", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "ClassLoading Metrics",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(servers.*.ClassLoading.*)"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "GC Timeline",
   "type": "graph",
   "description": "Show all garbage collections that occur.",
   "gridPos": { "h": 6, "w": 16, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_typeName",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "typeName" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "GC",
     "select": [
      [
       { "params": [ "CollectionCount" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "target": "aliasByNode(removeBelowValue(derivative(*.*.GC.*.CollectionCount), 1), 3)"
    }
   ]
  },
  {
   "title": "GC Scavenge Collections",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 27 },
   "format": "none",
   "valueName": "min",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "GC",
     "select": [
      [
       { "params": [ "CollectionCount" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "typeName",
       "operator": "=",
       "value": "type=GarbageCollector,name=PS Scavenge"
      }
     ],
     "target": "*.*.GC.PSScavenge.CollectionCount"
    }
   ]
  },
  {
   "title": "GC Full Collections",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 27 },
   "format": "none",
   "valueName": "min",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "GC",
     "select": [
      [
       { "params": [ "CollectionCount" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "typeName",
       "operator": "=",
       "value": "type=GarbageCollector,name=PS MarkSweep"
      }
     ],
     "target": "*.*.GC.PSMarkSweep.CollectionCount"
    }
   ]
  },
  {
   "title": "Heap Memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "Used",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "attributeName" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "heap",
     "query": "SELECT mean(\"committed\") FROM \"heap\" WHERE $timeFilter GROUP BY time($__interval), \"hostname\" fill(null)",
     "select": [
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "attributeName", "operator": "=", "value": "HeapMemoryUsage" }
     ],
     "target": "aliasByMetric(*.*.heap.HeapMemoryUsage_used)"
    },
    {
     "alias": "Used",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "attributeName" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "heap",
     "query": "SELECT mean(\"committed\") FROM \"heap\" WHERE $timeFilter GROUP BY time($__interval), \"hostname\" fill(null)",
     "select": [
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "attributeName", "operator": "=", "value": "HeapMemoryUsage" }
     ],
     "target": "aliasByMetric(*.*.heap.HeapMemoryUsage_committed)"
    },
    {
     "alias": "Used",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "attributeName" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "heap",
     "query": "SELECT mean(\"committed\") FROM \"heap\" WHERE $timeFilter GROUP BY time($__interval), \"hostname\" fill(null)",
     "select": [
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "attributeName", "operator": "=", "value": "HeapMemoryUsage" }
     ],
     "target": "aliasByMetric(*.*.heap.HeapMemoryUsage_max)"
    }
   ]
  },
  {
   "title": "Non-Heap Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "Used",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "attributeName" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "heap",
     "query": "SELECT mean(\"committed\") FROM \"heap\" WHERE $timeFilter GROUP BY time($__interval), \"hostname\" fill(null)",
     "select": [
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "attributeName", "operator": "=", "value": "NonHeapMemoryUsage" }
     ],
     "target": "aliasByMetric(*.*.heap.NonHeapMemoryUsage_used)"
    },
    {
     "alias": "Committed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "attributeName" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "heap",
     "query": "SELECT mean(\"committed\") FROM \"heap\" WHERE $timeFilter GROUP BY time($__interval), \"attributeName\" fill(none)",
     "select": [
      [
       { "params": [ "committed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "attributeName", "operator": "=", "value": "NonHeapMemoryUsage" }
     ]
    },
    {
     "alias": "Used",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "attributeName" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "heap",
     "query": "SELECT mean(\"committed\") FROM \"heap\" WHERE $timeFilter GROUP BY time($__interval), \"hostname\" fill(null)",
     "select": [
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "attributeName", "operator": "=", "value": "NonHeapMemoryUsage" }
     ],
     "target": "aliasByMetric(*.*.heap.NonHeapMemoryUsage_committed)"
    }
   ]
  }
 ]
}