{
 "title": "InfluxDB Internals",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Database Information",
   "type": "table",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "database" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "database",
     "select": [
      [
       { "params": [ "numMeasurements" ], "type": "field" }
      ],
      [
       { "params": [ "numSeries" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "WAL Cur Seg Disk Bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_database",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "database" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "tsm1_wal",
     "select": [
      [
       { "params": [ "currentSegmentDiskBytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "TSM1 Caching",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "Cached",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "tsm1_cache",
     "select": [
      [
       { "params": [ "cachedBytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Disk",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "tsm1_cache",
     "select": [
      [
       { "params": [ "diskBytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Memory",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "tsm1_cache",
     "select": [
      [
       { "params": [ "memBytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}