{
 "title": "Disk View Dashboard",
 "tags": [ "NetAppESeries" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "System",
    "query": "SHOW TAG VALUES ON \"eseries\" FROM \"disks\" WITH KEY = \"sys_name\""
   },
   {
    "name": "Tray",
    "query": "SHOW TAG VALUES FROM disks WITH KEY = \"sys_tray\" WHERE \"sys_name\" =~ /$System/"
   },
   {
    "name": "Slot",
    "query": "SHOW TAG VALUES FROM disks WITH KEY = \"sys_tray_slot\" WHERE \"sys_name\" =~ /$System/ AND \"sys_tray\" =~ /$Tray/"
   }
  ]
 },
 "panels": [
  {
   "title": "Average Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sys_name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "disks",
     "query": "SELECT mean(\"combinedResponseTime\") FROM \"disks\" WHERE (\"sys_name\" =~ /^$System$/ AND \"sys_tray\" =~ /^$Tray$/) AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "combinedResponseTime" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sys_name", "operator": "=~", "value": "/^$System$/" },
      { "condition": "AND", "key": "sys_tray", "operator": "=~", "value": "/^$Tray$/" },
      { "condition": "AND", "key": "sys_tray_slot", "operator": "=~", "value": "/^$Slot$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sys_name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "disks",
     "query": "SELECT mean(\"ds_combinedResponseTime\") FROM \"downsample_retention\".\"disks\" WHERE (\"sys_name\" =~ /^$System$/ AND \"sys_tray\" =~ /^$Tray$/ AND \"sys_tray_slot\" =~ /^$Slot$/) AND $timeFilter AND time < now() - 1w GROUP BY time($__interval), \"sys_name\" fill(none)",
     "select": [
      [
       { "params": [ "combinedResponseTime" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sys_name", "operator": "=~", "value": "/^$System$/" },
      { "condition": "AND", "key": "sys_tray", "operator": "=~", "value": "/^$Tray$/" },
      { "condition": "AND", "key": "sys_tray_slot", "operator": "=~", "value": "/^$Slot$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "MBs" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sys_name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "disks",
     "query": "SELECT sum(\"combinedThroughput\") FROM \"disks\" WHERE (\"sys_name\" =~ /^$System$/ AND \"sys_tray\" =~ /^$Tray$/ AND \"sys_tray_slot\" =~ /^$Slot$/) AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "combinedThroughput" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "sys_name", "operator": "=~", "value": "/^$System$/" },
      { "condition": "AND", "key": "sys_tray", "operator": "=~", "value": "/^$Tray$/" },
      { "condition": "AND", "key": "sys_tray_slot", "operator": "=~", "value": "/^$Slot$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sys_name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "disks",
     "query": "SELECT sum(\"ds_combinedThroughput\") FROM \"downsample_retention\".\"disks\" WHERE (\"sys_name\" =~ /^$System$/ AND \"sys_tray\" =~ /^$Tray$/ AND \"sys_tray_slot\" =~ /^$Slot$/) AND $timeFilter AND time < now() - 1w GROUP BY time($__interval), \"sys_name\" fill(none)",
     "select": [
      [
       { "params": [ "combinedThroughput" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "sys_name", "operator": "=~", "value": "/^$System$/" },
      { "condition": "AND", "key": "sys_tray", "operator": "=~", "value": "/^$Tray$/" },
      { "condition": "AND", "key": "sys_tray_slot", "operator": "=~", "value": "/^$Slot$/" }
     ]
    }
   ]
  },
  {
   "title": "Total IOPs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sys_name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "disks",
     "query": "SELECT sum(\"combinedIOps\") FROM \"disks\" WHERE (\"sys_name\" =~ /^$System$/ AND \"sys_tray\" =~ /^$Tray$/ AND \"sys_tray_slot\" =~ /^$Slot$/) AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "combinedIOps" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "sys_name", "operator": "=~", "value": "/^$System$/" },
      { "condition": "AND", "key": "sys_tray", "operator": "=~", "value": "/^$Tray$/" },
      { "condition": "AND", "key": "sys_tray_slot", "operator": "=~", "value": "/^$Slot$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sys_name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "disks",
     "query": "SELECT sum(\"ds_combinedIOps\") FROM \"downsample_retention\".\"disks\" WHERE (\"sys_name\" =~ /^$System$/ AND \"sys_tray\" =~ /^$Tray$/ AND \"sys_tray_slot\" =~ /^$Slot$/) AND $timeFilter AND time < now() - 1w GROUP BY time($__interval), \"sys_name\" fill(none)",
     "select": [
      [
       { "params": [ "combinedIOps" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "sys_name", "operator": "=~", "value": "/^$System$/" },
      { "condition": "AND", "key": "sys_tray", "operator": "=~", "value": "/^$Tray$/" },
      { "condition": "AND", "key": "sys_tray_slot", "operator": "=~", "value": "/^$Slot$/" }
     ]
    }
   ]
  },
  {
   "title": "Average Read Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sys_name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "disks",
     "query": "SELECT mean(\"readResponseTime\") FROM \"disks\" WHERE (\"sys_name\" =~ /^$System$/ AND \"sys_tray\" =~ /^$Tray$/ AND \"sys_tray_slot\" =~ /^$Slot$/) AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "readResponseTime" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sys_name", "operator": "=~", "value": "/^$System$/" },
      { "condition": "AND", "key": "sys_tray", "operator": "=~", "value": "/^$Tray$/" },
      { "condition": "AND", "key": "sys_tray_slot", "operator": "=~", "value": "/^$Slot$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sys_name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "disks",
     "query": "SELECT mean(\"ds_readResponseTime\") FROM \"downsample_retention\".\"disks\" WHERE (\"sys_name\" =~ /^$System$/ AND \"sys_tray\" =~ /^$Tray$/ AND \"sys_tray_slot\" =~ /^$Slot$/) AND $timeFilter AND time < now() - 1w GROUP BY time($__interval), \"sys_name\" fill(none)",
     "select": [
      [
       { "params": [ "readResponseTime" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sys_name", "operator": "=~", "value": "/^$System$/" },
      { "condition": "AND", "key": "sys_tray", "operator": "=~", "value": "/^$Tray$/" },
      { "condition": "AND", "key": "sys_tray_slot", "operator": "=~", "value": "/^$Slot$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Read Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "MBs" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sys_name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "disks",
     "query": "SELECT sum(\"readThroughput\") FROM \"disks\" WHERE (\"sys_name\" =~ /^$System$/ AND \"sys_tray\" =~ /^$Tray$/ AND \"sys_tray_slot\" =~ /^$Slot$/) AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "readThroughput" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "sys_name", "operator": "=~", "value": "/^$System$/" },
      { "condition": "AND", "key": "sys_tray", "operator": "=~", "value": "/^$Tray$/" },
      { "condition": "AND", "key": "sys_tray_slot", "operator": "=~", "value": "/^$Slot$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sys_name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "disks",
     "query": "SELECT sum(\"ds_readThroughput\") FROM \"downsample_retention\".\"disks\" WHERE (\"sys_name\" =~ /^$System$/ AND \"sys_tray\" =~ /^$Tray$/ AND \"sys_tray_slot\" =~ /^$Slot$/) AND $timeFilter AND time < now() - 1w GROUP BY time($__interval), \"sys_name\" fill(none)",
     "select": [
      [
       { "params": [ "readThroughput" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "sys_name", "operator": "=~", "value": "/^$System$/" },
      { "condition": "AND", "key": "sys_tray", "operator": "=~", "value": "/^$Tray$/" },
      { "condition": "AND", "key": "sys_tray_slot", "operator": "=~", "value": "/^$Slot$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Read IOPs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sys_name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "disks",
     "query": "SELECT sum(\"readIOps\") FROM \"disks\" WHERE (\"sys_name\" =~ /^$System$/ AND \"sys_tray\" =~ /^$Tray$/ AND \"sys_tray_slot\" =~ /^$Slot$/) AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "readIOps" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "sys_name", "operator": "=~", "value": "/^$System$/" },
      { "condition": "AND", "key": "sys_tray", "operator": "=~", "value": "/^$Tray$/" },
      { "condition": "AND", "key": "sys_tray_slot", "operator": "=~", "value": "/^$Slot$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sys_name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "disks",
     "query": "SELECT sum(\"ds_readIOps\") FROM \"downsample_retention\".\"disks\" WHERE (\"sys_name\" =~ /^$System$/ AND \"sys_tray\" =~ /^$Tray$/ AND \"sys_tray_slot\" =~ /^$Slot$/) AND $timeFilter AND time < now() - 1w GROUP BY time($__interval), \"sys_name\" fill(none)",
     "select": [
      [
       { "params": [ "readIOps" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "sys_name", "operator": "=~", "value": "/^$System$/" },
      { "condition": "AND", "key": "sys_tray", "operator": "=~", "value": "/^$Tray$/" },
      { "condition": "AND", "key": "sys_tray_slot", "operator": "=~", "value": "/^$Slot$/" }
     ]
    }
   ]
  },
  {
   "title": "Average Write Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sys_name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "disks",
     "query": "SELECT mean(\"writeResponseTime\") FROM \"disks\" WHERE (\"sys_name\" =~ /^$System$/ AND \"sys_tray\" =~ /^$Tray$/ AND \"sys_tray_slot\" =~ /^$Slot$/) AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "writeResponseTime" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sys_name", "operator": "=~", "value": "/^$System$/" },
      { "condition": "AND", "key": "sys_tray", "operator": "=~", "value": "/^$Tray$/" },
      { "condition": "AND", "key": "sys_tray_slot", "operator": "=~", "value": "/^$Slot$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sys_name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "disks",
     "query": "SELECT mean(\"ds_writeResponseTime\") FROM \"downsample_retention\".\"disks\" WHERE (\"sys_name\" =~ /^$System$/ AND \"sys_tray\" =~ /^$Tray$/ AND \"sys_tray_slot\" =~ /^$Slot$/) AND $timeFilter AND time < now() - 1w GROUP BY time($__interval), \"sys_name\" fill(none)",
     "select": [
      [
       { "params": [ "writeResponseTime" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sys_name", "operator": "=~", "value": "/^$System$/" },
      { "condition": "AND", "key": "sys_tray", "operator": "=~", "value": "/^$Tray$/" },
      { "condition": "AND", "key": "sys_tray_slot", "operator": "=~", "value": "/^$Slot$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Write Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "MBs" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sys_name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "disks",
     "select": [
      [
       { "params": [ "writeThroughput" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "sys_name", "operator": "=~", "value": "/^$System$/" },
      { "condition": "AND", "key": "sys_tray", "operator": "=~", "value": "/^$Tray$/" },
      { "condition": "AND", "key": "sys_tray_slot", "operator": "=~", "value": "/^$Slot$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sys_name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "disks",
     "query": "SELECT sum(\"writeThroughput\") FROM \"downsample_retention\".\"disks\" WHERE (\"sys_name\" =~ /^$System$/ AND \"sys_tray\" =~ /^$Tray$/ AND \"sys_tray_slot\" =~ /^$Slot$/) AND $timeFilter AND time < now() - 1w GROUP BY time($__interval), \"sys_name\" fill(none)",
     "select": [
      [
       { "params": [ "writeThroughput" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "sys_name", "operator": "=~", "value": "/^$System$/" },
      { "condition": "AND", "key": "sys_tray", "operator": "=~", "value": "/^$Tray$/" },
      { "condition": "AND", "key": "sys_tray_slot", "operator": "=~", "value": "/^$Slot$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Write IOPs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sys_name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "disks",
     "select": [
      [
       { "params": [ "writeIOps" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "sys_name", "operator": "=~", "value": "/^$System$/" },
      { "condition": "AND", "key": "sys_tray", "operator": "=~", "value": "/^$Tray$/" },
      { "condition": "AND", "key": "sys_tray_slot", "operator": "=~", "value": "/^$Slot$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sys_name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "disks",
     "query": "SELECT sum(\"ds_writeIOps\") FROM \"downsample_retention\".\"disks\" WHERE (\"sys_name\" =~ /^$System$/ AND \"sys_tray\" =~ /^$Tray$/ AND \"sys_tray_slot\" =~ /^$Slot$/) AND $timeFilter AND time < now() - 1w GROUP BY time($__interval), \"sys_name\" fill(none)",
     "select": [
      [
       { "params": [ "writeIOps" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "sys_name", "operator": "=~", "value": "/^$System$/" },
      { "condition": "AND", "key": "sys_tray", "operator": "=~", "value": "/^$Tray$/" },
      { "condition": "AND", "key": "sys_tray_slot", "operator": "=~", "value": "/^$Slot$/" }
     ]
    }
   ]
  }
 ]
}